[theme]
inherit = basic
stylesheet = css/theme.css
pygments_style = default
pygments_dark_style = monokai

[options]
nav_title =
logo_icon =
color_primary = #2c3e50
color_accent = #3498db
globaltoc_depth = 5
globaltoc_collapse = true
globaltoc_includehidden = true
google_analytics_account =
base_url =
chat_enabled = false
chat_api_key =
chat_pipeline_id =
chat_api_url =
chat_provider = runllm
feedback_enabled = false
feedback_formspree_id =
feedback_provider = formspree
sidebar_footer_links =
